sudo: required
services:
  - docker
before_install:
  - docker build -t jayghevariya/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jayghevariya/docker-react npm run test -- --coverage  # -- --coverage is used to exit the test after running # CI=true 