name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
        uses: actions/checkout@v2
      
    - name: Generate Deployment Package
      uses: zip -r deploy.zip * -x "**node_modules**"

    - name: Get time stamp
      uses: gerred/actions/current-time@master
      id: current-time